#
###################################
# Site wide configuration
####################################
#
title: 이번 삽은 얼마나 갈까
email:
description: The amy's portfolio blog
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll", "amy"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: amymeme
  avatar: profile.png
  job: "Server Developer"
  bio: "삽은 많다. 이번 삽은 얼마나 갈까."
  email: cgc8016@ewhain.net
  disqus-shortname: #
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: AMYMEME
  gitlab: #username
  stackoverflow: #12804021/amy
  linkedin: seulgi-choi-b8623519b
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
